#!/usr/bin/env python3
"""Reproduce this suite's local installations from pinned upstream releases."""
import argparse
import hashlib
import io
import json
from pathlib import Path
import platform
import re
import shlex
import subprocess
import sys
import tarfile
import urllib.request

ROOT = Path(__file__).resolve().parent.parent


def installation_mode(argv):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--system", action="store_true",
                        help="Install into the current non-venv Python; explicitly allow pip --break-system-packages")
    parser.add_argument("--shell", choices=("zsh", "bash", "none"), default="none",
                        help="Add or update TinkerTom's block in the selected user's shell startup file")
    args = parser.parse_args(argv)
    in_venv = sys.prefix != sys.base_prefix
    if args.system and in_venv:
        parser.error("--system requires a Python outside a venv. Deactivate it or choose your system Python explicitly.")
    if not args.system and not in_venv:
        parser.error("Use .venv/bin/python scripts/install-tools.py, or explicitly select --system for a non-venv install.")
    if sys.version_info < (3, 11):
        parser.error("TinkerTom requires Python 3.11 or newer.")
    return args


def write_launcher(binary_dir, name, distribution):
    # pip's script directory can differ from the interpreter's directory (e.g.
    # /usr/bin/python3 with scripts under /usr/local/bin or ~/.local/bin).
    # Bind the suite launchers to this interpreter instead of guessing a path.
    code = ("import sys; from importlib.metadata import distribution; "
            f"sys.argv[0] = {name!r}; "
            f"sys.exit(next(e for e in distribution({distribution!r}).entry_points "
            f"if e.group == 'console_scripts' and e.name == {name!r}).load()())")
    script = "#!/bin/sh\n# Generated by TinkerTom's installer.\nexec " + shlex.join([sys.executable, "-c", code]) + ' "$@"\n'
    target = binary_dir / name
    if target.is_symlink():
        target.unlink()  # Never write through an old launcher symlink.
    target.write_text(script)
    target.chmod(0o755)


def install_python_packages(pins, system):
    command = [sys.executable, "-m", "pip", "install"]
    if system:
        command.append("--break-system-packages")
    command += ["--only-binary=headroom-ai", "-e", str(ROOT), pins["headroom"]["distribution"],
                pins["chat"]["distribution"], pins["native_transport"]["distribution"]]
    subprocess.run(command, check=True)


def configure_shell(shell):
    if shell == "none":
        return
    profile = Path.home() / (".zshrc" if shell == "zsh" else ".bashrc")
    start, end = "# >>> TinkerTom setup >>>", "# <<< TinkerTom setup <<<"
    block = start + "\nsource " + shlex.quote(str(ROOT / "shell" / ("tinkertom." + shell))) + "\n" + end
    contents = profile.read_text() if profile.exists() else ""
    pattern = re.compile(r"(?ms)^" + re.escape(start) + r"\n.*?^" + re.escape(end) + r"$")
    if start in contents or end in contents:
        if contents.count(start) != 1 or contents.count(end) != 1 or not pattern.search(contents):
            raise SystemExit(f"Incomplete/duplicate TinkerTom setup markers in {profile}; file left unchanged.")
        updated = pattern.sub(lambda _: block, contents, count=1)
    else:
        updated = contents + ("\n" if contents and not contents.endswith("\n") else "") + "\n" + block + "\n"
    if updated != contents:
        profile.write_text(updated)
    print("Shell integration configured in " + str(profile))


def main(argv=None):
    args = installation_mode(argv)
    pins = json.loads((ROOT / "tools.lock.json").read_text())
    binary_dir = ROOT / ".tools/bin"
    binary_dir.mkdir(parents=True, exist_ok=True)
    for name in ("rtk", "headroom", "beads"):
        pin = pins[name]
        source = ROOT / ".tools/src" / name
        if not source.exists():
            subprocess.run(["git", "clone", "--depth", "1", "--branch", pin["tag"], pin["repository"], str(source)], check=True)
        commit = subprocess.check_output(["git", "-C", str(source), "rev-parse", "HEAD"], text=True).strip()
        if commit != pin["commit"]:
            raise SystemExit(f"{source} is at a different revision; expected {pin['commit']}. Existing checkout left unchanged.")
    if platform.system() == "Linux" and platform.machine() == "x86_64":
        pin = pins["rtk"]
        binary = binary_dir / "rtk"
        if not binary.exists() or hashlib.sha256(binary.read_bytes()).hexdigest() != pin["binary_sha256"]:
            data = urllib.request.urlopen(pin["binary_url"], timeout=30).read()
            if hashlib.sha256(data).hexdigest() != pin["archive_sha256"]:
                raise SystemExit("RTK archive checksum mismatch")
            with tarfile.open(fileobj=io.BytesIO(data)) as archive:
                member = next(m for m in archive.getmembers() if Path(m.name).name == "rtk" and m.isfile())
                binary.write_bytes(archive.extractfile(member).read())
                binary.chmod(0o755)
    else:
        subprocess.run(["cargo", "install", "--locked", "--path", str(ROOT / ".tools/src/rtk"), "--root", str(ROOT / ".tools")], check=True)
    if platform.system() == "Linux" and platform.machine() == "x86_64":
        pin = pins["beads"]
        binary = binary_dir / "bd"
        if not binary.exists() or hashlib.sha256(binary.read_bytes()).hexdigest() != pin["binary_sha256"]:
            data = urllib.request.urlopen(pin["binary_url"], timeout=30).read()
            if hashlib.sha256(data).hexdigest() != pin["archive_sha256"]:
                raise SystemExit("Beads archive checksum mismatch")
            with tarfile.open(fileobj=io.BytesIO(data)) as archive:
                member = next(m for m in archive.getmembers() if Path(m.name).name == "bd" and m.isfile())
                contents = archive.extractfile(member).read()
                if hashlib.sha256(contents).hexdigest() != pin["binary_sha256"]:
                    raise SystemExit("Beads binary checksum mismatch")
                binary.write_bytes(contents)
                binary.chmod(0o755)
    elif not (binary_dir / "bd").exists():
        raise SystemExit("Install Beads for this platform using its official instructions; this lock pins the Linux x86_64 binary.")
    install_python_packages(pins, args.system)
    for name, distribution in (("headroom", "headroom-ai"), ("tinkertom", "tinkertom")):
        write_launcher(binary_dir, name, distribution)
    # Vocab caching is best-effort. Compression uses estimates if downloads are
    # unavailable; this is a public tokenizer vocabulary, not a model/API call.
    cache = ROOT / ".tools/tokenizer-cache"
    cache.mkdir(exist_ok=True)
    for name, expected in (("o200k_base", "446a9538cb6c348e3516120d7c08b09f57c36495e2acfffe59a5bf8b0cfb1a2d"),):
        url = f"https://openaipublic.blob.core.windows.net/encodings/{name}.tiktoken"
        target = cache / hashlib.sha1(url.encode()).hexdigest()
        if target.exists():
            continue
        try:
            data = urllib.request.urlopen(url, timeout=5).read()
            if hashlib.sha256(data).hexdigest() != expected:
                raise ValueError("Tokenizer checksum mismatch")
            target.write_bytes(data)
        except (OSError, ValueError) as exc:
            print(f"Tokenizer cache unavailable ({exc}); Headroom can use estimates.")
    configure_shell(args.shell)
    print("Suite installed with " + sys.executable)
    print("Run " + shlex.join([str(binary_dir / "tinkertom"), "doctor"]))
    if args.shell == "none":
        print("For zsh, add this line to ~/.zshrc: source " + shlex.quote(str(ROOT / "shell/tinkertom.zsh")))


if __name__ == "__main__":
    main()
